twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/reset_password': reset_password
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
